export const textRandomizer = async () => {
  
    const comentarios = [
    "¡Increíble!",
    "Me encantó esto 😍",
    "Muy bueno 👍",
    "Jajaja qué bueno",
    "No me lo esperaba",
    "Está genial 🔥",
    "Excelente contenido",
    "Buenísimo 💯",
    "Me hizo el día 😂",
    "Qué locura esto",
    "Demasiado bueno",
    "Me encantó la idea",
    "Súper interesante",
    "Top 🔝",
    "De lo mejor que vi hoy",
    "Muy creativo",
    "Qué buen trabajo",
    "Brutal 🔥",
    "Simplemente wow",
    "Me gustó mucho esto",
    "Joya total",
    "Está muy bien hecho",
    "Qué calidad 👌",
    "Sos crack",
    "Increíble aporte",
    "Me sirvió mucho",
    "Buenísimo esto",
    "No paro de verlo",
    "Está muy piola",
    "Me representa 😂",
    "Qué buen contenido",
    "Excelente explicación",
    "Muy entretenido",
    "Esto es oro puro",
    "Me encantó 😄",
    "Súper útil",
    "Genial idea",
    "Qué bien explicado",
    "Muy original",
    "Lo necesitaba",
    "Está perfecto",
    "Me sorprendió",
    "Qué locura 🔥",
    "Muy buena vibra",
    "Me gustó bastante",
    "Está de 10",
    "Qué buenísimo",
    "Lo amé ❤️",
    "Muy recomendable",
    "Sigue así 💪"
  ];
  const random = comentarios[Math.floor(Math.random() * comentarios.length)];

  return random;
};

export const userRandomizer = async () => {

  const usuarios = [
    "juan_dev",
    "maria.codes",
    "lucas23",
    "sofii_ok",
    "el_tomi",
    "agus.exe",
    "nicolas_dev",
    "camii_98",
    "franco.tech",
    "valen_art",
    "maxi.gg",
    "lautaro_x",
    "emi_dev",
    "roci.codes",
    "fede_ok",
    "martu_22",
    "gabi.pro",
    "nacho_dev",
    "luli_x",
    "tobi_77",
    "alan.js",
    "vicky.dev",
    "dani_ok",
    "cande_99",
    "santi.exe",
    "brisa_art",
    "facu.dev",
    "mica.codes",
    "leo_tech",
    "tati_x",
    "joaco.gg",
    "meli_ok",
    "ivan.dev",
    "zoe_22",
    "mati.js",
    "flor_codes",
    "axel.tech",
    "paula.dev",
    "thiago_x",
    "eve.codes",
    "rami_ok",
    "sol_98",
    "bauti.dev",
    "alma.art",
    "martin.gg",
    "julii_x",
    "benja.tech",
    "candela.dev",
    "reno_ok",
    "luu_codes"
  ];

  const random = usuarios[Math.floor(Math.random() * usuarios.length)];

  return random;
};